version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongodb-dev
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - data-network

  redis:
    image: redis:latest
    container_name: redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - data-network

volumes:
  mongo_data:
    driver: local
  redis_data:
    driver: local

networks:
  data-network:
    driver: bridge
